AWSTemplateFormatVersion: "2010-09-09"
Description: 'CloudFormation template - Checks/notifies age of AWS keys for included users'
Parameters:
    ageThreshold:
        Type: String
        Description: "Max age for keys before alerting"
        Default: "90"
Resources:
    CheckAccessKeys:
      Type: 'AWS::Lambda::Function'
      Properties:
          Handler: 'check_access_keys.lambda_handler'
          Role: !GetAtt LambdaExecutionRole.Arn
          Runtime: python3.6
          Timeout: 10
          Code: .

    LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                  - Effect: Allow
                    Principal: {Service: [lambda.amazonaws.com]}
                    Action: ['sts:AssumeRole']
            Path: /
            ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
                -   PolicyName: PublishAndExcecute
                    PolicyDocument:
                        Version: 2012-10-17
                        Statement:
                            -   Effect: Allow
                                Action: ['lambda:PublishVersion']
                                Resource: '*' #!Join ["", ["arn:aws:lambda:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":function:", !Ref CheckAccessKeys]]
                            -   Effect: Allow
                                Action: ['logs:CreateLogGroup','logs:CreateLogStream', 'logs:PutLogEvents']
                                Resource: 'arn:aws:logs:*:*:*'
                            -   Effect: Allow
                                Action: ['iam:ListAccessKeys', 'iam:ListUsers']
                                Resource: '*'
                            -   Effect: Allow
                                Action: ['sns:Publish']
                                Resource: !Ref SnsTopic

    SnsTopic:
        Type: AWS::SNS::Topic
        Properties:
            Subscription:
            - Endpoint: sys.admin <sys.admin@emii.org.au>
              Protocol: email


    CloudWatchEvent:
        Type: "AWS::Events::Rule"
        Properties:
            Description: Triggers application cron
            ScheduleExpression: "rate(15 days)"
            State: ENABLED
            Targets:
            - Arn: !GetAtt CheckAccessKeys.Arn
              Id: "CheckAccessKeys"
              Input: !Join [ "", [ "{   \"excluded_users\": [\"anonymous\", \"ses-smtp-user.metadataentry\"],   \"topic\": \"", !Ref SnsTopic, "\",   \"age_threshold\": \"", !Ref ageThreshold, "\" }" ]]
