---
# assert a file exists on a host filesystem or s3

- name: Gather facts from pipeline-processing-servers
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - facter
  delegate_to: "{{ server_item }}"
  delegate_facts: True
  loop: "{{ groups['pipeline-processing-servers'] }}"
  loop_control:
    loop_var: server_item

- name: "list files in s3 bucket"
  shell: "aws s3 ls --recursive {{ stack_integration.bucket_name }}/{{ assert_config.remote_file }} | awk '{print $4}'"
  register: objects_list
  delegate_to: localhost
  when: hostvars['pipeline']['file_store_type'] == 's3'

- name: "list files in file system"
  find:
    paths: "{{ hostvars['pipeline']['file_store'] }}/{{ assert_config.remote_file | dirname }}"
    patterns: "{{ assert_config.remote_file | basename }}"
  delegate_to: pipeline
  register: file_list
  when: hostvars['pipeline']['file_store_type'] == 'file'

- set_fact:
    file_list: "{{ objects_list.stdout_lines }}"
  when: hostvars['pipeline']['file_store_type'] == 's3'

- set_fact:
    file_list: "{{ file_list.files }}"
  when: hostvars['pipeline']['file_store_type'] == 'file'

- block:
    - name: "Assert {{ assert_config.remote_file }} exists"
      assert:
        that:
          - file_list is defined and (file_list | length > 0)
        fail_msg: "{{ assert_config.remote_file }} does not exist"
        success_msg: "{{ assert_config.remote_file }} exists"
      register: assertion_result
      when: assert_config.invert is not defined or assert_config.invert == false
    - name: "Assert {{ assert_config.remote_file }} does not exist"
      assert:
        that:
          - file_list is defined and (file_list | length == 0)
        fail_msg: "{{ assert_config.remote_file }} exists"
        success_msg: "{{ assert_config.remote_file }} does not exist"
      register: assertion_result_inverted
      when: assert_config.invert is defined and assert_config.invert == true
  ignore_errors: yes  # Don't halt playbook but show the error in the ignored count in PLAY RECAP

# Workaround for https://github.com/ansible/ansible/issues/4297
- set_fact:
    assertion_result: "{{ assertion_result_inverted }}"
  when: assert_config.invert is defined and assert_config.invert == true

- set_fact:
    assertion_results: "{{ assertion_results +
    [ { 'Pipeline': name, 'name':item.name,
    'result': assertion_result.failed,
    'template': 'file_exists.j2',
    'template_vars': {'msg': {{ stack_integration.bucket_name }} + '/' + assertion_result.msg} } ] }}" # Add to results accumulator for report
