---
# if files to compare are large need to set ANSIBLE_MAX_DIFF_SIZE=10444800 environment variable
- set_fact:
    copy_src_root: "{{ assert_config.content }}"
    copy_dest_root: "{{ assert_config.expected }}"
- name: "diff harvested results against expected results"
  delegate_to: localhost
  copy:
    src: "{{ copy_src_root }}/{{ item.path }}"
    dest: "{{ copy_dest_root }}/{{ item.path }}"
  check_mode: yes  # don't copy just check results
  diff: yes
  register: diffresult
  with_filetree: "{{ assert_config.content }}/"  # diff all the files in the directory
  when: item.state == 'file'
- block:
  - assert:
      that:
        - diffresult.changed == false
      fail_msg: "{{ name }} harvested results do not match expected results"
      success_msg: "{{ name }} harvested results match expected results"
  ignore_errors: yes  # Don't halt playbook but show the error in the ignored count in PLAY RECAP
