---
- set_fact:
    assertion_results: []

- include_tasks:
    file: "assert_{{ item.name.split(':')[0] }}.yaml"
  vars:
    assert_config: "{{ item }}"
  loop: "{{ assertions }}"

- set_fact:
    all_assertion_results: "{{ all_assertion_results + assertion_results }}"
