actions:
- incoming:
  - dest: AUV
    local_file: DATA_Tasmania201808_r20180823_054016_SS07_Beagle_Shelf_15.csv
  type: ADD
- incoming:
  - dest: AUV
    local_file: DATA_Tasmania201808_r20180823_054016_SS07_Beagle_Shelf_15.csv.update
    remote_file: DATA_Tasmania201808_r20180823_054016_SS07_Beagle_Shelf_15.csv
  type: UPDATE
- incoming:
  - dest: AUV
    local_file: DATA_Tasmania201808_r20180823_215013_SS08_Beagle_Shelf_13.csv
  type: ADD
- file: IMOS/AUV/auv_viewer_data/csv_outputs/Tasmania201808/DATA_Tasmania201808_r20180823_215013_SS08_Beagle_Shelf_13.csv
  type: DELETE
- incoming:
  - dest: AUV
    local_file: auvReporting.csv
  type: ADD
- incoming:
  - dest: AUV
    local_file: auvReporting.csv.update
    remote_file: auvReporting.csv
  type: UPDATE
assertions:
- content: auv_viewer_track
  expected: ../test_configs/auv_viewer_track/expect
  name: diff
database_schemas:
- name: auv_viewer_track
  tables:
  - exclude_columns: []
    name: auv_images_vw
  - exclude_columns: []
    name: auv_tracks_vw
  - exclude_columns: []
    name: auv_reporting
drop_schema_objects: true
name: auv_viewer_track
po: laurent
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- auv_viewer_track-auv_viewer_track
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.AUV.log
test_report_template: test_results
type: pipeline_version_2
