---
- set_fact:
    test_config_full_path: "{{ inventory_dir | dirname }}/{{ test_config }}"
    stack_integration_full_path: "{{ inventory_dir | dirname }}/stack_integration.json"

- include_vars:
    file: "{{ stack_integration_full_path }}"

- delegate_to: localhost
  stat:
    path: "{{ test_config_full_path }}"
  register: stat_test_config

- name: "List configurations from directories"
  delegate_to: localhost
  find:
    path: "{{ test_config_full_path }}"
    file_type: directory
    recurse: no
  register: test_config_directories
  when: stat_test_config.stat.isdir is defined and stat_test_config.stat.isdir

- include_tasks:
    file: "{{ task_file }}"
  vars:
    test_config_file: "{{ test_config_item.path }}/config.yaml"
  loop: "{{ test_config_directories.files }}"
  loop_control:
    loop_var: test_config_item
  when: stat_test_config.stat.isdir is defined and stat_test_config.stat.isdir

- include_tasks:
    file: "{{ task_file }}"
  vars:
    test_config_file: "{{ test_config_full_path }}"
  when: stat_test_config.stat.isreg is defined and stat_test_config.stat.isreg