database_connection:
  login_user: imosadmin
  login_password: imosadmin

  # UNCOMMENT ONE SECTION ONLY, RDS/non-RDS

  ## start non-RDS
  #login_host: localhost
  ## end non-RDS

  ## start RDS
  rds: true
  stack_name: harvest-rc-ansible-test
  ## end RDS

database:
  name: harvest

database_profiles:
  - harvest

postgresql_extensions:
  - postgis

postgresql_roles:
  - name: lwgordon
    password: qwerty12345
  - name: lwgordon1
    password: qwerty123456
  - name: angus
    password: qwerty123456543534534534

postgresql_schemas:
  - schema: public
    owner: imosadmin
  - schema: qwertyschema
    owner: lwgordon
  - schema: qwertyschema_angus
    owner: angus
