- name: manage roles from Chef 'postgresql_roles' databag item
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.privileges | default([]) | join(',') }}"
    db: "{{ database.name }}"
    state: "{{ item.state | default('present') }}"
    login_host: "{{ database_endpoint }}"
    login_password: "{{ database_connection.login_password }}"
    login_user: "{{ database_connection.login_user }}"
    port: "{{ database_connection.port | default(omit) }}"
  with_items: "{{ chef_roles_databag['roles'] }}"
