actions:
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_BFZ_20150127T000000Z_SRC_FV02_EcoTriplet-daily.nc
    remote_file: IMOS_SRS-OC-LJCO_BFZ_20150201T000000Z_SRC_FV02_EcoTriplet-daily.nc
  type: ADD
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_BFZ_20150201T000000Z_SRC_FV02_EcoTriplet-daily.nc
  type: UPDATE
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_EFZ_20180717T000000Z_SRC_FV02_HyperOCR-daily.nc
    remote_file: IMOS_SRS-OC-LJCO_EFZ_20180721T000000Z_SRC_FV02_HyperOCR-daily.nc
  type: ADD
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_EFZ_20180721T000000Z_SRC_FV02_HyperOCR-daily.nc
  type: UPDATE
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_FTZ_20180713T000000Z_SRC_FV02_ACS-daily-wcc.nc
    remote_file: IMOS_SRS-OC-LJCO_FTZ_20180717T000000Z_SRC_FV02_ACS-daily-wcc.nc
  type: ADD
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_FTZ_20180717T000000Z_SRC_FV02_ACS-daily-wcc.nc
  type: UPDATE
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_FZ_20140322T000000Z_SRC_FV02_BB9-daily.nc
    remote_file: IMOS_SRS-OC-LJCO_FZ_20140325T000000Z_SRC_FV02_BB9-daily.nc
  type: ADD
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_FZ_20140325T000000Z_SRC_FV02_BB9-daily.nc
  type: UPDATE
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_KOSTUZ_20140404T003500Z_SRC_FV02_WQM-daily.nc
    remote_file: IMOS_SRS-OC-LJCO_KOSTUZ_20140408T003500Z_SRC_FV02_WQM-daily.nc
  type: ADD
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_KOSTUZ_20140408T003500Z_SRC_FV02_WQM-daily.nc
  type: UPDATE
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_KOSTUZ_20150915T074210Z_SRC_FV01_WQM-hourly.nc
    remote_file: IMOS_SRS-OC-LJCO_KOSTUZ_20150915T114210Z_SRC_FV01_WQM-hourly.nc
  type: ADD
- incoming:
  - dest: SRS/OC/LJCO
    local_file: IMOS_SRS-OC-LJCO_KOSTUZ_20150915T114210Z_SRC_FV01_WQM-hourly.nc
  type: UPDATE
assertions:
- content: srs_oc_ljco_wws
  expected: srs_oc_ljco_wws/expect
  name: diff
- name: file_exists:1
  remote_file: SRS/OC/LJCO/IMOS_SRS-OC-LJCO_BFZ_20150201T000000Z_SRC_FV02_EcoTriplet-daily.nc
- name: file_exists:2
  remote_file: SRS/OC/LJCO/IMOS_SRS-OC-LJCO_EFZ_20180721T000000Z_SRC_FV02_HyperOCR-daily.nc
- name: file_exists:3
  remote_file: SRS/OC/LJCO/IMOS_SRS-OC-LJCO_FTZ_20180717T000000Z_SRC_FV02_ACS-daily-wcc.nc
- name: file_exists:4
  remote_file: SRS/OC/LJCO/IMOS_SRS-OC-LJCO_FZ_20140325T000000Z_SRC_FV02_BB9-daily.nc
- name: file_exists:5
  remote_file: SRS/OC/LJCO/IMOS_SRS-OC-LJCO_KOSTUZ_20140408T003500Z_SRC_FV02_WQM-daily.nc
- name: file_exists:6
  remote_file: SRS/OC/LJCO/IMOS_SRS-OC-LJCO_KOSTUZ_20150915T114210Z_SRC_FV01_WQM-hourly.nc
database_schemas:
- name: srs_oc_ljco_wws
  tables:
  - exclude_columns: []
    name: srs_oc_ljco_wws_daily_acs_fv02_timeseries_map
  - exclude_columns: []
    name: srs_oc_ljco_wws_daily_all_products_fv02_timeseries_map
  - exclude_columns: []
    name: srs_oc_ljco_wws_daily_bb9_fv02_timeseries_map
  - exclude_columns: []
    name: srs_oc_ljco_wws_daily_ecotriplet_fv02_timeseries_map
  - exclude_columns: []
    name: srs_oc_ljco_wws_daily_ecotriplet_fv02_timeseries_data
  - exclude_columns: []
    name: srs_oc_ljco_wws_daily_hyperocr_fv02_timeseries_map
  - exclude_columns: []
    name: srs_oc_ljco_wws_daily_wqm_fv02_timeseries_map
  - exclude_columns: []
    name: srs_oc_ljco_wws_daily_wqm_fv02_timeseries_data
  - exclude_columns: []
    name: srs_oc_ljco_wws_hourly_wqm_fv01_timeseries_map
  - exclude_columns: []
    name: srs_oc_ljco_wws_hourly_wqm_fv01_timeseries_data
  - exclude_columns: []
    name: srs_oc_ljco_wws_mtw_monthly_fv01_timeseries_map
  - exclude_columns: []
    name: srs_oc_ljco_wws_mtw_monthly_fv01_timeseries_water_data
  - exclude_columns: []
    name: srs_oc_ljco_wws_mtw_monthly_fv01_timeseries_weather_data
drop_schema_objects: true
name: srs_oc_ljco_wws
po: loz
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- srs_oc_ljco_wws-srs_oc_ljco_wws
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.SRS_OC_LJCO.log
test_report_template: test_results
type: pipeline_version_2
