
# Stack template for generating a bucket and user with necessary access to that bucket
#   for the purposes of geowebcache blob storage


Parameters:
 
  UserName:
    Type: String
    Description: name for geowebcache user
  
  BucketName:
    Type: String
    Description: name for S3 bucket for geowebcache blob storage

Resources:
 
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !Sub ${BucketName}

  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${UserName}
      Policies:
      - PolicyName: !Sub ${BucketName}-s3-bucket-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
              Resource:
                - arn:aws:s3:::*
            - Effect: Allow
              Action:
                - s3:DeleteObject
                - s3:Get*
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: 
                - !Sub "arn:aws:s3:::${BucketName}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetBucketAcl
              Resource:
                - !Sub arn:aws:s3:::${BucketName}
         
