AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AODN template: production iam resources

Parameters:
  MonitorBucket1:
    Type: String

Resources:

  MonitorInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref MonitorRole

  MonitorRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "production-iam-nagios-monitor-bucket1"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - s3:ListBucket
                Resource: 
                  - !Sub arn:aws:s3:::${MonitorBucket1}
