actions:
- incoming:
  - dest: ABOS/DA
    local_file: EAC2000-2018.subset.zip
  type: ADD
- incoming:
  - dest: ABOS/DA
    local_file: EAC2000-2018.subset.updated.zip
    remote_file: EAC2000-2018.subset.zip
  type: UPDATE
- path: IMOS/ABOS/DA/EAC2000
  type: DELETE
assertions:
- content: abos_da
  expected: abos_da/expect
  name: diff
database_schemas:
- name: abos_currents
  tables:
  - exclude_columns: []
    name: abos_currents_map
- name: anmn_metadata
  tables:
  - exclude_columns:
    - date_published
    - date_updated
    name: abos_all_map
- name: abos_ts
  tables:
  - exclude_columns: []
    name: abos_ts_timeseries_data
  - exclude_columns: []
    name: abos_ts_timeseries_map
drop_schema_objects: true
name: abos_da
po: marty
process_report_template: processing_results
run_talend_liqui: false
talend_jobs:
- abos_currents-abos_currents
- moorings_metadata-moorings_metadata
- abos_ts-abos_ts
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.ABOS_DA.log
test_report_template: test_results
type: pipeline_version_2
