actions:
- incoming:
  - dest: SRS/SURFACE_WAVES/altimeter_trigger
    local_file: IMOS_SRS-Surface-Waves_MW_CRYOSAT-2_FV02_001S-260E-DM00.nc
    remote_file: IMOS_SRS-Surface-Waves_MW_CRYOSAT-2_FV02_003S-268E-DM00.nc
  type: ADD
- incoming:
  - dest: SRS/SURFACE_WAVES/altimeter_trigger
    local_file: IMOS_SRS-Surface-Waves_MW_CRYOSAT-2_FV02_003S-268E-DM00.nc
  type: UPDATE
- incoming:
  - dest: SRS/SURFACE_WAVES/altimeter_trigger
    local_file: IMOS_SRS-Surface-Waves_MW_CRYOSAT-2_FV02_003S-269E-DM00.nc
  type: ADD
- file: IMOS/SRS/Surface-Waves/Wave-Wind-Altimetry-DM00/CRYOSAT-2/020S_260E/IMOS_SRS-Surface-Waves_MW_CRYOSAT-2_FV02_003S-269E-DM00.nc
  type: DELETE
assertions:
- content: srs_surface_waves
  expected: ../test_configs/srs_surface_waves/expect
  name: diff
database_schemas:
- name: srs_surface_waves
  tables:
  - exclude_columns: []
    name: timeseries
  - exclude_columns:
    - created
    - modified
    - first_indexed
    - last_indexed
    name: indexed_file
drop_schema_objects: true
name: srs_surface_waves
po: loz
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- srs_surface_waves-srs_surface_waves
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.SRS_SURFACE_WAVES.log
test_report_template: test_results
type: pipeline_version_2
