actions:
- incoming:
  - dest: ANMN/SA
    local_file: IMOS_ANMN-NRS_T_20110320T010000Z_NRSKAI_FV02_NRSKAI-1103-gridded_END-20110718T230000Z.nc
  type: ADD
- file: IMOS/ANMN/NRS/NRSKAI/Temperature/gridded/IMOS_ANMN-NRS_T_20110320T010000Z_NRSKAI_FV02_NRSKAI-1103-gridded_END-20110718T230000Z.nc
  type: DELETE
- incoming:
  - dest: ANMN/SA
    local_file: IMOS_ANMN-NRS_T_20110719T010000Z_NRSKAI_FV02_NRSKAI-1107-gridded_END-20111219T230000Z.nc
    remote_file: IMOS_ANMN-NRS_T_20111220T010000Z_NRSKAI_FV02_NRSKAI-1112-gridded_END-20120415T010000Z.nc
  type: ADD
- incoming:
  - dest: ANMN/SA
    local_file: IMOS_ANMN-NRS_T_20111220T010000Z_NRSKAI_FV02_NRSKAI-1112-gridded_END-20120415T010000Z.nc
  type: UPDATE
assertions:
- content: anmn_t_regridded
  expected: anmn_t_regridded/expect
  name: diff
database_schemas:
- name: anmn_t_regridded
  tables:
  - exclude_columns: []
    name: anmn_regridded_temperature_data
  - exclude_columns: []
    name: anmn_regridded_temperature_map
drop_schema_objects: true
name: anmn_t_regridded
po: bene
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- anmn_t_regridded-anmn_t_regridded
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.ANMN_SA.log
test_report_template: test_results
type: pipeline_version_2
