AWSTemplateFormatVersion: "2010-09-09"
Description: AODN RDS template
Parameters:
  DBName:
    Type: String
  DBPassword:
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  DBUsername:
    Type: String
    Default: imosadmin
Resources:
    DBParameterGroup:
        Type: AWS::RDS::DBParameterGroup
        Properties:
          Description: AODN 9.6 parameter group
          Family: postgres9.6
          Parameters:
            log_statement: all
            max_connections: '120'
    DBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: '5'
        DBInstanceClass: db.t2.micro
        DBName: !Ref DBName
        DBParameterGroupName: !Ref DBParameterGroup
        Engine: postgres
        EngineVersion: 9.6
        MasterUsername: !Ref DBUsername
        MasterUserPassword: !Ref DBPassword
        BackupRetentionPeriod: 0
        PubliclyAccessible: true
      DeletionPolicy: Delete
Outputs:
  DatabaseEndpoint:
    Value: !GetAtt DBInstance.Endpoint.Address
  JDBCConnectionString:
    Value: !Join [ '', [ 'jdbc:postgresql://', !GetAtt DBInstance.Endpoint.Address, ':', !GetAtt [DBInstance, Endpoint.Port], /, !Ref DBName ] ]
