actions:
- incoming:
  - dest: FAIMMS
    local_file: IMOS_FAIMMS_T_20160101T000000Z_DAVSF1_FV00.nc
    remote_file: IMOS_FAIMMS_T_20160201T000000Z_DAVSF1_FV00.md5.nc
  type: ADD
- incoming:
  - dest: FAIMMS
    local_file: IMOS_FAIMMS_T_20160201T000000Z_DAVSF1_FV00.nc
    remote_file: IMOS_FAIMMS_T_20160201T000000Z_DAVSF1_FV00.md5.nc
  type: UPDATE
- incoming:
  - dest: FAIMMS
    local_file: IMOS_FAIMMS_T_20160101T000000Z_DAVSF1_FV01.nc
    remote_file: IMOS_FAIMMS_T_20160101T000000Z_DAVSF1_FV01.md5.nc
  type: ADD
- incoming:
  - dest: FAIMMS
    local_file: IMOS_FAIMMS_T_20160201T000000Z_DAVSF1_FV01.nc
    remote_file: IMOS_FAIMMS_T_20160201T000000Z_DAVSF1_FV01.md5.nc
  type: ADD
- file: IMOS/FAIMMS/Davies_Reef/Sensor_Float_1/sea_water_temperature@0.6m_channel_270/2016/QAQC/IMOS_FAIMMS_T_20160101T000000Z_DAVSF1_FV01.nc
  type: DELETE
assertions:
- content: faimms
  expected: faimms/expect
  name: diff
- name: file_exists:1
  remote_file: FAIMMS/IMOS_FAIMMS_T_20160201T000000Z_DAVSF1_FV00.md5.nc
- name: file_exists:2
  remote_file: FAIMMS/IMOS_FAIMMS_T_20160101T000000Z_DAVSF1_FV01.md5.nc
- name: file_exists:3
  remote_file: FAIMMS/IMOS_FAIMMS_T_20160201T000000Z_DAVSF1_FV01.md5.nc
- invert: true
  name: file_exists:not:3
  remote_file: IMOS/FAIMMS/Davies_Reef/Sensor_Float_1/sea_water_temperature@0.6m_channel_270/2016/QAQC/IMOS_FAIMMS_T_20160101T000000Z_DAVSF1_FV01.nc
database_schemas:
- name: faimms
  tables:
  - exclude_columns: []
    name: faimms_timeseries_map
  - exclude_columns: []
    name: faimms_timeseries_data
drop_schema_objects: true
name: faimms
po: laurent
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- faimms-faimms
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.FAIMMS.log
test_report_template: test_results
type: pipeline_version_2
