actions:
- incoming:
  - dest: ANMN/NSW
    local_file: PH100.zip
  type: ADD
- incoming:
  - dest: ANMN/NSW
    local_file: PH100.updated.zip
    remote_file: PH100.zip
  type: UPDATE
- file: IMOS/ANMN/NSW/PH100/Velocity/IMOS_ANMN-NSW_AETVZ_20170227T190000Z_PH100_FV01_PH100-1702-Sentinel-or-Monitor-Workhorse-ADCP-109.5_END-20170527T030500Z_C-20180117T000000Z.nc
  type: DELETE
- file: IMOS/ANMN/NSW/PH100/Biogeochem_timeseries/burst-averaged/IMOS_ANMN-NSW_BCDKOSTUZ_20170227T015944Z_PH100_FV02_PH100-1702-WQM-15-burst-averaged_END-20170415T001455Z_C-20170905T161314Z.nc
  type: DELETE
- file: IMOS/ANMN/NSW/PH100/Biogeochem_profiles/IMOS_ANMN-NSW_CDEKOSTZ_20170716T224142Z_PH100_FV01_Profile-SBE19plus_C-20171103T040301Z.nc
  type: DELETE
- file: IMOS/ANMN/NSW/PH100/Temperature/IMOS_ANMN-NSW_TZ_20170224T130000Z_PH100_FV01_PH100-1702-Aqualogger-520PT-104_END-20170527T065500Z_C-20170905T035920Z.nc
  type: DELETE
- path: IMOS/ANMN/NSW/PH100
  type: DELETE
assertions:
- content: anmn_nsw
  expected: anmn_nsw/expect
  name: diff
database_schemas:
- name: anmn_ts
  tables:
  - exclude_columns: []
    name: anmn_ts_timeseries_data
  - exclude_columns: []
    name: anmn_ts_timeseries_map
- name: anmn_burst_avg
  tables:
  - exclude_columns: []
    name: anmn_burst_avg_timeseries_data
  - exclude_columns: []
    name: anmn_burst_avg_timeseries_map
- name: anmn_nrs_ctd_profiles
  tables:
  - exclude_columns: []
    name: anmn_nrs_ctd_profiles_data
  - exclude_columns: []
    name: anmn_nrs_ctd_profiles_map
- name: anmn_velocity
  tables:
  - exclude_columns: []
    name: anmn_velocity_timeseries_map
- name: anmn_metadata
  tables:
  - exclude_columns:
    - date_published
    - date_updated
    name: anmn_all_map
drop_schema_objects: true
name: anmn_nsw
po: marty
process_report_template: processing_results
run_talend_liqui: false
talend_jobs:
- anmn_ts_timeseries-anmn_ts_timeseries
- anmn_burst_avg_timeseries-anmn_burst_avg_timeseries
- anmn_nrs_ctd_profiles-anmn_nrs_ctd_profiles
- anmn_adcp_timeseries-anmn_adcp_timeseries
- moorings_metadata-moorings_metadata
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.ANMN_NSW.log
test_report_template: test_results
type: pipeline_version_2
