actions:
- incoming:
  - dest: SOOP/CO2
    local_file: FutureReefMap_GST_20121210T100429Z_9V2768_FV01.nc
  type: ADD
- incoming:
  - dest: SOOP/CO2
    local_file: FutureReefMap_GST_20121210T100429Z_9V2768_FV01.nc.original
    remote_file: FutureReefMap_GST_20121210T100429Z_9V2768_FV01.nc
  type: UPDATE
- incoming:
  - dest: SOOP/CO2
    local_file: FutureReefMap_GST_20130204T153916Z_9V2768_FV01.nc
  type: ADD
- file: Future_Reef_MAP/underway/RTM-Wakmatha/2013/WK201302N/FutureReefMap_GST_20130204T153916Z_9V2768_FV01.nc
  type: DELETE
assertions:
- content: future_reef_map
  expected: future_reef_map/expect
  name: diff
- name: file_exists:1
  remote_file: Future_Reef_MAP/underway/RTM-Wakmatha/2012/WK201212N/FutureReefMap_GST_20121210T100429Z_9V2768_FV01.nc
- name: file_exists:2
  remote_file: Future_Reef_MAP/underway/RTM-Wakmatha/2013/WK201302N/FutureReefMap_GST_20130204T153916Z_9V2768_FV01.nc
- invert: true
  name: file_exists:not:2
  remote_file: Future_Reef_MAP/underway/RTM-Wakmatha/2013/WK201302N/FutureReefMap_GST_20130204T153916Z_9V2768_FV01.nc
database_schemas:
- name: future_reef_map
  tables:
  - exclude_columns:
    - colour
    name: future_reef_map_trajectory_map
drop_schema_objects: true
name: future_reef_map
po: laurent_bene
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- future_reef_map-future_reef_map
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.SOOP_CO2.log
test_report_template: test_results
type: pipeline_version_2
enabled: true
