actions:
- incoming:
  - dest: AODN/ANMN_NRS_DAR_YON
    local_file: IMOS_ANMN_F_20190101T000000Z_NRSDAR_FV00.nc
    remote_file: IMOS_ANMN_F_20190201T000000Z_NRSDAR_FV00.md5.nc
  type: ADD
- incoming:
  - dest: AODN/ANMN_NRS_DAR_YON
    local_file: IMOS_ANMN_F_20190201T000000Z_NRSDAR_FV00.nc
    remote_file: IMOS_ANMN_F_20190201T000000Z_NRSDAR_FV00.md5.nc
  type: UPDATE
- incoming:
  - dest: AODN/ANMN_NRS_DAR_YON
    local_file: IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV00.nc
    remote_file: IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV00.md5.nc
  type: ADD
- file: IMOS/ANMN/NRS/REAL_TIME/NRSDAR/surface_downwelling_photosynthetic_radiative_flux_in_air@18.0m_channel_84316/2019/NO_QAQC/IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV00.nc
  type: DELETE
- incoming:
  - dest: AODN/ANMN_NRS_DAR_YON
    local_file: IMOS_ANMN_F_20190101T000000Z_NRSDAR_FV01.nc
    remote_file: IMOS_ANMN_F_20190201T000000Z_NRSDAR_FV01.md5.nc
  type: ADD
- incoming:
  - dest: AODN/ANMN_NRS_DAR_YON
    local_file: IMOS_ANMN_F_20190201T000000Z_NRSDAR_FV01.nc
    remote_file: IMOS_ANMN_F_20190201T000000Z_NRSDAR_FV01.md5.nc
  type: UPDATE
- incoming:
  - dest: AODN/ANMN_NRS_DAR_YON
    local_file: IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV01.nc
    remote_file: IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV01.md5.nc
  type: ADD
- file: IMOS/ANMN/NRS/REAL_TIME/NRSDAR/surface_downwelling_photosynthetic_radiative_flux_in_air@18.0m_channel_84316/2019/QAQC/IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV01.nc
  type: DELETE
assertions:
- content: anmn_nrs_dar_yon
  expected: anmn_nrs_dar_yon/expect
  name: diff
- name: file_exists:1
  remote_file: IMOS/AODN/ANMN_NRS_DAR_YON/IMOS_ANMN_F_20190201T000000Z_NRSDAR_FV00.md5.nc
- name: file_exists:2
  remote_file: IMOS/AODN/ANMN_NRS_DAR_YON/IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV00.md5.nc
- invert: true
  name: file_exists:not:2
  remote_file: IMOS/ANMN/NRS/REAL_TIME/NRSDAR/surface_downwelling_photosynthetic_radiative_flux_in_air@18.0m_channel_84316/2019/NO_QAQC/IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV00.nc
- name: file_exists:3
  remote_file: IMOS/AODN/ANMN_NRS_DAR_YON/IMOS_ANMN_F_20190201T000000Z_NRSDAR_FV01.md5.nc
- name: file_exists:4
  remote_file: IMOS/AODN/ANMN_NRS_DAR_YON/IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV01.md5.nc
- invert: true
  name: file_exists:not:4
  remote_file: IMOS/ANMN/NRS/REAL_TIME/NRSDAR/surface_downwelling_photosynthetic_radiative_flux_in_air@18.0m_channel_84316/2019/QAQC/IMOS_ANMN_F_20190301T000000Z_NRSDAR_FV01.nc
database_schemas:
- name: anmn_nrs_dar_yon
  tables:
  - exclude_columns: []
    name: anmn_nrs_dar_yon_timeseries_map
  - exclude_columns: []
    name: anmn_nrs_dar_yon_timeseries_data
drop_schema_objects: true
name: anmn_nrs_dar_yon
po: laurent
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- anmn_nrs_dar_yon-anmn_nrs_dar_yon
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.ANMN_NRS_DAR_YON.log
test_report_template: test_results
type: pipeline_version_2
