actions:
- incoming:
  - dest: /var/incoming/SOOP/TRV
    local_file: IMOS_SOOP-TRV_S_20190328T191556Z_VMQ9273_FV01_END-20190407T215725Z.nc
  type: ADD
assertions:
- content: soop_trv
  expected: ../test_configs/soop_trv/expect
  name: diff
database_schemas:
- name: soop_trv
  tables:
  - exclude_columns: []
    name: soop_trv_trajectory_data
  - exclude_columns:
    - colour
    name: soop_trv_trajectory_map
drop_schema_objects: true
name: soop_trv
po: laurent
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- soop_trv-soop_trv
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.SOOP_TRV.log
test_report_template: test_results
type: pipeline_version_2
