actions:
- incoming:
  - dest: SOOP/CO2
    local_file: IMOS_SOOP-CO2_GST_20110301T061948Z_FHZI_FV01.nc
  type: ADD
- file: IMOS/SOOP/SOOP-CO2/FHZI_Astrolabe/2011/AL1011_R4_northbound/IMOS_SOOP-CO2_GST_20110301T061948Z_FHZI_FV01.nc
  type: DELETE
- incoming:
  - dest: SOOP/CO2
    local_file: IMOS_SOOP-CO2_GST_20101031T113003Z_FHZI_FV01.nc.original
    remote_file: IMOS_SOOP-CO2_GST_20101031T113003Z_FHZI_FV01.nc
  type: ADD
- incoming:
  - dest: SOOP/CO2
    local_file: IMOS_SOOP-CO2_GST_20101031T113003Z_FHZI_FV01.nc
  type: UPDATE
assertions:
- content: soop_co2
  expected: ../test_configs/soop_co2/expect
  name: diff
database_schemas:
- name: soop_co2
  tables:
  - exclude_columns: []
    name: soop_co2_trajectory_data
  - exclude_columns:
    - colour
    name: soop_co2_trajectory_map
drop_schema_objects: true
name: soop_co2
po: bene
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- soop_co2-soop_co2
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.SOOP_CO2.log
test_report_template: test_results
type: pipeline_version_2
