actions:
- incoming:
  - dest: SOOP/CO2
    local_file: IMOS_SOOP-CO2_GST_20190503T000516Z_VLMJ_FV00_END-20190503T005908Z.nc
    remote_file: IMOS_SOOP-CO2_GST_20190505T000348Z_VLMJ_FV00_END-20190506T000107Z.nc
  type: ADD
- incoming:
  - dest: SOOP/CO2
    local_file: IMOS_SOOP-CO2_GST_20190505T000348Z_VLMJ_FV00_END-20190506T000107Z.nc
  type: UPDATE
- incoming:
  - dest: SOOP/CO2
    local_file: IMOS_SOOP-CO2_GST_20190507T000515Z_VLMJ_FV00_END-20190508T000344Z.nc
  type: ADD
- file: IMOS/SOOP/SOOP-CO2/VLMJ_Investigator/REALTIME/2019/5/IMOS_SOOP-CO2_GST_20190507T000515Z_VLMJ_FV00_END-20190508T000344Z.nc
  type: DELETE
assertions:
- content: soop_co2_rt
  expected: soop_co2_rt/expect
  name: diff
- name: file_exists:1
  remote_file: IMOS/SOOP/CO2/IMOS_SOOP-CO2_GST_20190505T000348Z_VLMJ_FV00_END-20190506T000107Z.nc
- name: file_exists:2
  remote_file: IMOS/SOOP/CO2/IMOS_SOOP-CO2_GST_20190507T000515Z_VLMJ_FV00_END-20190508T000344Z.nc
- invert: true
  name: file_exists:not:2
  remote_file: IMOS/SOOP/SOOP-CO2/VLMJ_Investigator/REALTIME/2019/5/IMOS_SOOP-CO2_GST_20190507T000515Z_VLMJ_FV00_END-20190508T000344Z.nc
database_schemas:
- name: soop_co2_rt
  tables:
  - exclude_columns:
    - colour
    name: soop_co2_rt_trajectory_map
  - exclude_columns: []
    name: soop_co2_rt_trajectory_data
drop_schema_objects: true
name: soop_co2_rt
po: bene
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- soop_co2_rt-soop_co2_rt
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.SOOP_CO2.log
test_report_template: test_results
type: pipeline_version_2
enabled: false
