actions:
- incoming:
  - dest: SOOP/TMV
    local_file: IMOS_SOOP-TMV_TSUB_20190311T100151Z_VLST_FV00_transect-M2D_END-20190311T192400Z.nc
    remote_file: IMOS_SOOP-TMV_TSUB_20190313T085121Z_VLST_FV00_transect-M2D_END-20190313T184130Z.nc
  type: ADD
- incoming:
  - dest: SOOP/TMV
    local_file: IMOS_SOOP-TMV_TSUB_20190313T085121Z_VLST_FV00_transect-M2D_END-20190313T184130Z.nc
  type: UPDATE
- incoming:
  - dest: SOOP/TMV
    local_file: IMOS_SOOP-TMV_TSUB_20190315T084741Z_VLST_FV00_transect-M2D_END-20190315T182040Z.nc
  type: ADD
- file: IMOS/SOOP/SOOP-TMV/VLST_Spirit-of-Tasmania-1/realtime/transect/1sec/2019/IMOS_SOOP-TMV_TSUB_20190315T084741Z_VLST_FV00_transect-M2D_END-20190315T182040Z.nc
  type: DELETE
assertions:
- content: soop_tmv
  expected: soop_tmv/expect
  name: diff
database_schemas:
- name: soop_tmv
  tables:
  - exclude_columns:
    - colour
    name: soop_tmv_nrt_trajectory_map
  - exclude_columns: []
    name: soop_tmv_nrt_trajectory_data
drop_schema_objects: true
name: soop_tmv
po: laurent
process_report_template: processing_results
run_talend_liqui: true
talend_jobs:
- soop_tmv-soop_tmv
talend_log_file: /mnt/ebs/log/pipeline/process/tasks.SOOP_TMV_NRT.log
test_report_template: test_results
type: pipeline_version_2
