---
- name: "diff harvested results against expected results"
  delegate_to: localhost
  copy:
    src: "../harvest_results/{{ hosts }}/{{ name }}/{{ item.path }}"
    dest: "../test_configs/{{ name }}/expect/{{ item.path }}"
  check_mode: yes  # don't copy just check results
  diff: yes
  register: diffresult
  with_filetree: "../harvest_results/{{ hosts }}/{{ name }}/"  # diff all the files in the directory
  when: item.state == 'file'
- assert:
    that:
      - diffresult.changed == false
    fail_msg: "{{ name }} harvested results do not match expected results"
    success_msg: "{{ name }} harvested results match expected results"
