---
- name: test talend
  hosts: "{{ hosts }}"
  gather_facts: no

  roles:
    - integration_tests

  vars_files:
    - global_vars.yaml

  vars:
    harvester_timeout: "{{ timeout|default(default_timeout) }}"
