---
# EXAMPLE (all test configs, provide a directory): ansible-playbook ansible/playbook_process.yaml -i test_configs/hosts --extra-vars "test_config=../test_configs"
# EXAMPLE (single test config, provide a file): ansible-playbook ansible/playbook_process.yaml -i test_configs/hosts --extra-vars "test_config=../test_configs/soop_trv/config.yaml"
# EXAMPLE (create expect data): ansible-playbook ansible/playbook_process.yaml -i test_configs/hosts --extra-vars "test_config=../test_configs/soop_trv/config.yaml create_expect=true"
- name: Process files in pipeline
  hosts: "pipeline"
  gather_facts: no

  roles:
    - process_files
