---
- name: Process files in pipeline
  hosts: "pipeline"
  gather_facts: true

  roles:
    - role: pipeline_processing
    - role: report
      vars:
         template: "{{ process_report_template }}"
